version: '3.8'
services:
    app:
        build: .
        volumes:
            - .:/var/www
        expose:
            - "9000"     # only needs to be accessible to nginx
        depends_on:
            - db

    web:
        image: nginx:latest
        ports:
            - "8000:80"       # Host port 8000 maps to Nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
            - app

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
